Repository AyushiPanth/FOSS-Design-Prototyping, pull requests merged in 2022-03, with the labels that each got.

#11 Solves #6 Issue
  fosslogo.png
Labels: accepted-5

#9 added leaderboard prototype
  Leaderborad.jpg
Labels: accepted-4

#13 #5 prototype_leaderboard
  LIT2021021_#LEADERBOARD.jpeg
Labels: accepted-4

#12 issue#5
  LIT2021018_arpita.jpeg
Labels: accepted-4

#10 added foss logo
  FOSS.png
Labels: accepted-2

#16 Solves #5 Issue
  fossleaderboard.JPG
Labels: accepted-3

#17 E Commerce
  ECommerce.png
Labels: accepted-2

#18 App Wireframe
  Kaustuv_AppWireframe.jpg
Labels: accepted-4

#19 College Website
  Website.png
Labels: accepted-2

#20 Foss Logo
  Foss.png
Labels: accepted-2

#22 Added E-Commerce App Prototype
  app.jpg
Labels: accepted-2

#21 added college website prototype
  iiitl_1.jpg
  iiitl_2.jpg
Labels: accepted-2

#23 Foss Logo
  Kaustuv_FossLogo.png
Labels: accepted-2
